name: multibench
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex  # Removed specific versions
  - blas=1.0=openblas
  - ca-certificates
  - certifi
  - libffi
  - ncurses
  - numpy  # Removed version constraint
  - openssl
  - pip
  - python=3.9  # Use a compatible Python version
  - readline
  - scipy  # Removed version constraint
  - setuptools
  - sqlite
  - tk
  - tzdata
  - wheel
  - xz
  - zlib
  - pip:
    - aiosignal==1.2.0
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - asttokens==2.0.5
    - attrs==21.4.0
    - backcall==0.2.0
    - beautifulsoup4==4.11.1
    - bleach
    - cffi==1.15.0
    - charset-normalizer==2.0.12
    - click==8.1.3
    - cloudpickle==2.1.0
    - cvxpy==1.4.1
    - cycler==0.11.0
    - debugpy==1.6.0
    - decorator==5.1.1
    - defusedxml==0.7.1
    - distlib==0.3.4
    - entrypoints==0.4
    - executing==0.8.3
    - fastjsonschema==2.15.3
    - filelock==3.7.1
    - fonttools==4.33.3
    - frozenlist==1.3.0
    - future==0.18.2
    - grpcio==1.43.0
    - h5py==3.6.0
    - hyperopt==0.2.7
    - idna==3.3
    - ipykernel==6.14.0
    - ipython==8.4.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.7.0
    - jedi==0.18.1
    - jinja2==3.1.2
    - joblib==1.1.0
    - jsonschema==4.6.0
    - jupyter-client==7.3.4
    - jupyter-core==4.10.0
    - jupyterlab-pygments==0.2.2
    - jupyterlab-widgets==1.1.0
    - kiwisolver==1.4.2
    - markupsafe==2.1.1
    - matplotlib==3.5.2
    - matplotlib-inline==0.1.3
    - memory-profiler==0.60.0
    - mistune==0.8.4
    - msgpack==1.0.4
    - nbclient==0.6.4
    - nbconvert==6.5.0
    - nbformat==5.4.0
    - nest-asyncio==1.5.5
    - networkx==2.8.3
    - notebook==6.4.12
    - packaging==21.3
    - pandas==1.4.2
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==9.1.1
    - platformdirs==2.5.2
    - prometheus-client==0.14.1
    - prompt-toolkit==3.0.29
    - protobuf==3.20.1
    - psutil==5.9.0
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - py4j==0.10.9.5
    - pycparser==2.21
    - pygments==2.12.0
    - pyparsing==3.0.9
    - pyrsistent==0.18.1
    - python-dateutil==2.8.2
    - pytz==2022.1
    - pyyaml==6.0
    - pyzmq==23.1.0
    - ray==1.12.1
    - requests==2.27.1
    - scikit-learn==1.1.0
    - send2trash==1.8.0
    - soupsieve==2.3.2.post1
    - stack-data==0.2.0
    - tabulate==0.8.9
    - tensorboardx==2.5.1
    - terminado==0.15.0
    - threadpoolctl==3.1.0
    - tinycss2==1.1.1
    - torch==1.11.0
    - torchtext==0.12.0
    - torchvision==0.12.0
    - tornado==6.1
    - tqdm==4.64.0
    - traitlets==5.2.2.post1
    - typing-extensions==4.2.0
    - urllib3==1.26.9
    - virtualenv==20.14.1
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - widgetsnbextension==3.6.0